---
- name: Cloud | Configure VM Network And IP | Configure VM NIC 
  delegate_to: "{{ virt_api_bastion }}"
  become: False
  block:

    - name: Cloud | Configure VM Network and IP | vSphere | Install Virt Module Prerequists
      include_tasks: tasks/vsphere_modules_prerequists.yml
      run_once: True

    - name: Cloud | Configure VM Network and IP | vSphere | Configure VM NIC
      vmware_guest:
        hostname: "{{ vsphere_hostname }}"
        username: "{{ vsphere_username }}"
        password: "{{ vsphere_password }}"
        validate_certs: "{{ vsphere_validate_certs }}"
        datacenter: "{{ vsphere_datacenter }}"
        cluster: "{{ vsphere_cluster }}"
        state: present
        name: "{{ ansible_fqdn }}"
        networks:
        - name: "{{ vsphere_network }}"
          start_connected: true
          type: static
          ip: "{{ vm_network_ip4 }}"
          netmask: "{{ vm_network_ip4_netmask_prefix }}"
          device_type: vmxnet3
