---
- name: Cloud | Optimize Kernel Scheduler
  hosts: all
  become: True
  gather_facts: True
  collections:
    - redhatofficial.cloud_utils
  tasks:
    - import_role:
        name: optimize_kernel_scheduler
